server:
    port: RTCSTATS_SERVER_PORT
    metrics: RTCSTATS_SERVER_METRICS

s3:
    accessKeyId: RTCSTATS_S3_ACCESS_KEY_ID
    secretAccessKey: RTCSTATS_S3_SECRET_ACCESS_KEY
    region: RTCSTATS_S3_REGION
    bucket: RTCSTATS_S3_BUCKET

firehose:
    accessKeyId: RTCSTATS_FIREHOSE_ACCESS_KEY_ID
    secretAccessKey: RTCSTATS_FIREHOSE_SECRET_ACCESS_KEY
    region: RTCSTATS_FIREHOSE_REGION
    stream: RTCSTATS_FIREHOSE_STREAM

gcs:
    bucket: RTCSTATS_GCS_BUCKET

bigquery:
    dataset: RTCSTATS_BIGQUERY_DATASET
    table: RTCSTATS_BIGQUERY_TABLE
    maxFlushTime: RTCSTATS_BIGQUERY_MAX_FLUSH_TIME
    bufferSize: RTCSTATS_BIGQUERY_BUFFER_SIZE
