server:
    port: 9999
    metrics: 9998
    skipLoadBalancerIp: true
    # cert: certs/cert.pem
    # key: certs/key.pem

s3:
    accessKeyId:
    secretAccessKey:
    region:
    bucket:

firehose:
    accessKeyId:
    secretAccessKey:
    region:
    stream:

gcs:
    bucket:

bigquery:
    dataset:
    table:
    maxFlushTime:
    bufferSize:
