server:
    port: 9999
    metrics: 9998
    skipLoadBalancerIp: true

s3:
    accessKeyId:
    secretAccessKey:
    region:
    bucket:

firehose:
    accessKeyId:
    secretAccessKey:
    region:
    stream:

gcs:
    bucket: rtcstats

bigquery:
    dataset: rtcstats
    table: features
    maxFlushTime:
    bufferSize: 1
